### ISSUE TITLE
Fix handling of prefixes

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/aberowlweb#39] opened 2019-11-03 09:11 UTC
See https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1053
The OBO prefixes are not correctly (or rather: not consistently) used. Import from OBO should be fixed.

**Comment by aliraza995** [comment] 2019-11-04 10:59
The problem is fixed now. Apparently while syncing ontologies from obo and bio-portal we were updating the source file but we were not updating the titles of the ontologies which was misleading for the user to see a different title for the ontology acronym in aberowl. So we synced aberowl again with updated titles of the ontologies from both obo foundry and bioportal.

**Closed** 2019-11-05 06:32 UTC
Labels: important
